language: node_js
node_js: 12.18.2

services:
  - mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({ user:"travisCI", pwd:"test123", roles:["readWrite"] });'

install:
  - npm i

script:
  - npm test

deploy:
  provider: lambda
  function_name: "lambda-test"
  region: "us-east-1"
  # arn:aws:iam::933145830531:role/aws-elasticbeanstalk-service-role
  # role: "arn:aws:iam::0123456789012:role/lambda_basic_execution"
  runtime: "nodejs12.x"
  handler_name: "handler"
