# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CD

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
    - completed
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Mongodb
    steps:
    - uses: actions/checkout@v3
    
    - name: Invoke deployment hook
      uses: distributor/workflow-webhook@v2
      env:
        webhook_url: ${{secrets.DEPLOY_HOOK}}
        webhook_secret: ${{secrets.DEPLOY_HOOK}}
